%COMPE565 Homework 4
%Nov. 21, 2019
%Name: Seanmark Paz
%ID: 820246863
%Email: spaz@sdsu.edu

%File will be run from executing this README file

%Problem 1: P frame motion estimation
%Implementation: Exhaustive Search
%M-file name: COMPE565HW4.m
%Usage: Run COMPE565HW4.m file
%Location of output images: Figures will be generated by the code
disp('Running "COMPE565HW4"...');
COMPE565HW4;
disp('Done, "COMPE565HW4"');
